//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STF_CharacterPlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STF_CharacterPlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job:Starter
        ///Assassin:No
        ///Bounty Hunter:Yes
        ///Combat Medic:No
        ///Commander:No
        ///Crew Dog:No
        ///Diplomat:No
        ///Doctor:No
        ///Electronics Tech:No
        ///Engineer:No
        ///Exo-Scout:No
        ///Explorer:Yes
        ///Gunner:No
        ///Hyperwarp Navigator:No
        ///Mechanic:No
        ///Merchant:Yes
        ///Military Officer:Yes
        ///Pilot:No
        ///Pirate:Yes
        ///Pistoleer:No
        ///Quartermaster:No
        ///Smuggler:Yes
        ///Soldier:No
        ///Sniper:No
        ///Spy:Yes
        ///Swordsman:No
        ///Zealot:Yes
        ///None:No.
        /// </summary>
        internal static string job_list {
            get {
                return ResourceManager.GetString("job_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Size:Current Mass:Pilot:Ship Ops:Gunnery:Electronics:Navigation:Cargo:Max Crew:Max Officers:Armour:Shield:Jump Cost:Fuel Tank:Guest:Prison:Medical
        ///Adv. Mass Dampener 1:Medium:-300:0:4:0:0:0:0:0:0:0:0:0:0:0:0:0
        ///Adv. Mass Dampener 2:Medium:-330:0:4:0:2:0:0:0:0:0:0:0:0:0:0:0
        ///Adv. Mass Dampener 3:Medium:-360:0:5:0:1:0:0:0:0:0:0:0:0:0:0:0
        ///Adv. Mass Dampener 4:Medium:-400:0:5:0:2:0:0:0:0:0:0:0:0:0:0:0
        ///Aramech Missile Pod:Small:125:0:2:7:1:0:0:0:0:0:0:0:0:0:0:0
        ///Aramech X2 Missile Battery:Small:125:0:2:1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ship_components {
            get {
                return ResourceManager.GetString("ship_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill
        ///Blades
        ///Evasion
        ///Stealth
        ///Rifles
        ///Intimidate
        ///Pistols
        ///Doctor
        ///Tactics
        ///Command
        ///Ship Ops
        ///Gunnery
        ///Repair
        ///Negotiate
        ///Electronics
        ///Explore
        ///Navigation
        ///Pilot.
        /// </summary>
        internal static string skill_list {
            get {
                return ResourceManager.GetString("skill_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:1-Name:1-Num:2-Name:2-Num:3-Name:3-Num:Job
        ///1:Blades:2:Evasion:1:Stealth:1:Assassin
        ///2:Blades:3:Evasion:1:Stealth:3:Assassin
        ///3:Blades:4:Evasion:1:Stealth:3:Assassin
        ///4:Blades:4:Evasion:1:Stealth:4:Assassin
        ///5:Blades:5:Evasion:1:Stealth:4:Assassin
        ///6:Blades:5:Evasion:1:Stealth:5:Assassin
        ///7:Blades:5:Evasion:1:Stealth:6:Assassin
        ///8:Blades:6:Evasion:1:Stealth:6:Assassin
        ///9:Blades:6:Evasion:1:Stealth:7:Assassin
        ///10:Blades:6:Evasion:1:Stealth:8:Assassin
        ///11:Blades:7:Evasion:2:Stealth:8:Assassin
        ///12:Blades:7:Evasion:3: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skill_per_job_list {
            get {
                return ResourceManager.GetString("skill_per_job_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Mass:Speed:Agility:Fuel Cost:Combat Cost:Safety:Range Cost
        ///M2400 Void Engine:2400:27:27:2:6:4:3
        ///M2400 Void Engine-Longhaul:2400:27:27:1:10:5:3
        ///M3400 Void Engine-Traveler:3400:29:24:2:9:7:3
        ///M3400 Void Engine-Chaser:3400:24:29:2:10:6:2
        ///M3400 Void Engine:3400:24:24:2:8:5:3
        ///M3400 Void Engine-Longhaul:3400:23:23:1:7:7:3
        ///M5000 Void Engine-Traveler:5000:23:16:3:12:9:4
        ///M5000 Void Engine:5000:19:19:2:13:7:4
        ///M5000 Void Engine-Chaser:5000:18:22:2:15:8:3
        ///M6000 Void Engine-Longhaul:6000:15:15:2:16:8:4
        ///M6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stf_engine_data {
            get {
                return ResourceManager.GetString("stf_engine_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship:Current Mass:Max Mass:Price:Total Slots:Large:Mid:Small:Hull:Armour:Shield:Max Officers:Max Crew:Cargo:Engine:Speed:Agility:Fuel Cost:Fuel Tank:Fuel Range:Jump Cost:Pilot:Navigation:Ship Ops:Electronics:Gunnery:Tier
        /// Juror Class:3345:3400:$160.0k:15:2:3:10:1100:10:10:4:24:25:M3400 Void Engine-Balanced:24:24:2:95:47:21:11:13:20:11:15:2
        /// Paladin Cruiser:4990:5000:$260.0k:19:4:5:10:1500:8:7:5:30:50:M5000 Void Engine-Balanced:19:19:2:195:97:24:14:17:28:18:20:3
        /// Fidelis Cutter:5835:6000:$375.0k:23:4:7:12:20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STF_Ship_Data {
            get {
                return ResourceManager.GetString("STF_Ship_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship:Component
        ///Juror Class:M3400 Void Engine-Balanced
        ///Juror Class:Barracks 3
        ///Juror Class:Officer Cabin
        ///Juror Class:Cargo Hold 1
        ///Juror Class:Passenger Cabin
        ///Juror Class:Bridge
        ///Juror Class:M3400 Hyperwarp
        ///Juror Class:Light Railgun
        ///Juror Class:Hellfire Torpedo
        ///Juror Class:Weapons Locker A1
        ///Juror Class:Officer Cabin
        ///Juror Class:Armored Bulkheads
        ///Juror Class:Hellfire Torpedo
        ///Juror Class:Phoenix Lance
        ///Juror Class:Officer Cabin
        ///Paladin Cruiser:M5000 Void Engine-Balanced
        ///Paladin Cruiser:Officer Cabin
        ///Paladin Cruise [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STF_Ship_Default_Comp {
            get {
                return ResourceManager.GetString("STF_Ship_Default_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Rank:Description:Cooldown:Job:Type
        ///Expert Planning:1:Automatically passes a failed Tactics test in any situation, including on patrol, deep space travel, or during a mission:3 weeks Cooldown:Military Officer:Skill Save
        ///Power Play:1:When completing steps in a Mission, increase Faction Reputation bonuses by Charisma %:3 weeks Cooldown:Military Officer:Reputation
        ///Militant Patrol:1:When Patrolling a system, increase rewards by 10% + Command Skill:3 weeks Cooldown:Military Officer:Patrol
        ///Stiff Salute:1:When [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stf_talent_job {
            get {
                return ResourceManager.GetString("stf_talent_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Type:Damage:Radiation:Void:Range:AP:Accuracy:Critical Chance:Cripple Chance:Level
        ///Valiant Autocannon:Autocannon:65:0:0:1:1:1:5:30:1
        ///M90 Barrel-Cannon :Autocannon:135:0:0:1:2:2:12:45:2
        ///M92 Barrel-Cannon:Autocannon:75:0:0:1:1:3:15:40:3
        ///M94 Barrel-Cannon:Autocannon:160:0:0:1:2:5:10:55:4
        ///Dual-Linked Autocannon:Autocannon:85:0:0:1:1:6:20:30:5
        ///Vanguard Autocannon:Autocannon:100:0:0:1:1:6:15:25:6
        ///Lionheart Cannon:Autocannon:90:0:0:1:1:10:15:40:7
        ///Phoenix Lance:Lance:100:20:0:2:2:2:15:55:1
        ///Starshot Lan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stf_weapon_data {
            get {
                return ResourceManager.GetString("stf_weapon_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:Talents
        ///1:1
        ///3:1
        ///6:1
        ///9:1
        ///12:1
        ///15:1
        ///18:1
        ///21:1
        ///24:1
        ///27:1
        ///30:1
        ///32:1
        ///36:1
        ///.
        /// </summary>
        internal static string talent_points {
            get {
                return ResourceManager.GetString("talent_points", resourceCulture);
            }
        }
    }
}
