//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STF_CharacterPlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STF_CharacterPlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job:Starter
        ///Assassin:No
        ///Bounty Hunter:Yes
        ///Combat Medic:No
        ///Commander:No
        ///Crew Dog:No
        ///Diplomat:No
        ///Doctor:No
        ///Electronics Tech:No
        ///Engineer:No
        ///Exo-Scout:No
        ///Explorer:Yes
        ///Gunner:No
        ///Hyperwarp Navigator:No
        ///Mechanic:No
        ///Merchant:Yes
        ///Military Officer:Yes
        ///Pilot:No
        ///Pirate:Yes
        ///Pistoleer:No
        ///Quartermaster:No
        ///Smuggler:Yes
        ///Soldier:No
        ///Sniper:No
        ///Spy:Yes
        ///Swordsman:No
        ///Zealot:Yes.
        /// </summary>
        internal static string job_list {
            get {
                return ResourceManager.GetString("job_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill
        ///Blades
        ///Evasion
        ///Stealth
        ///Rifles
        ///Intimidate
        ///Pistols
        ///Doctor
        ///Tactics
        ///Command
        ///Ship Ops
        ///Gunnery
        ///Repair
        ///Negotiate
        ///Electronics
        ///Explore
        ///Navigation
        ///Pilot.
        /// </summary>
        internal static string skill_list {
            get {
                return ResourceManager.GetString("skill_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:1-Name:1-Num:2-Name:2-Num:3-Name:3-Num:Job
        ///1:Blades:2:Evasion:1:Stealth:1:Assassin
        ///2:Blades:3:Evasion:1:Stealth:3:Assassin
        ///3:Blades:4:Evasion:1:Stealth:3:Assassin
        ///4:Blades:4:Evasion:1:Stealth:4:Assassin
        ///5:Blades:5:Evasion:1:Stealth:4:Assassin
        ///6:Blades:5:Evasion:1:Stealth:5:Assassin
        ///7:Blades:5:Evasion:1:Stealth:6:Assassin
        ///8:Blades:6:Evasion:1:Stealth:6:Assassin
        ///9:Blades:6:Evasion:1:Stealth:7:Assassin
        ///10:Blades:6:Evasion:1:Stealth:8:Assassin
        ///11:Blades:7:Evasion:2:Stealth:8:Assassin
        ///12:Blades: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skill_per_job_list {
            get {
                return ResourceManager.GetString("skill_per_job_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:Rank:Description:Cooldown:Job:Type
        ///Expert Planning:1:Automatically passes a failed Tactics test in any situation, including on patrol, deep space travel, or during a mission:3 weeks Cooldown:Military Officer:Skill Save
        ///Power Play:1:When completing steps in a Mission, increase Faction Reputation bonuses by Charisma %:3 weeks Cooldown:Military Officer:Reputation
        ///Militant Patrol:1:When Patrolling a system, increase rewards by 10% + Command Skill:3 weeks Cooldown:Military Officer:Patrol
        ///Stiff Salute:1: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stf_talent_job {
            get {
                return ResourceManager.GetString("stf_talent_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:Talents
        ///1:1
        ///3:1
        ///6:1
        ///9:1
        ///12:1
        ///15:1
        ///18:1
        ///21:1
        ///24:1
        ///27:1
        ///30:1
        ///32:1
        ///36:1
        ///.
        /// </summary>
        internal static string talent_points {
            get {
                return ResourceManager.GetString("talent_points", resourceCulture);
            }
        }
    }
}
